"""Initial migration

Revision ID: 39fdbfa96bdf
Revises: 
Create Date: 2024-09-03 11:53:01.998822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fdbfa96bdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_authors')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('date_of_death',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('publication_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publication_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('date_of_death',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_authors',
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('date_of_death', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    # ### end Alembic commands ###
