"""Add purchase link to books

Revision ID: 3f069cf05997
Revises: af8e2b81b837
Create Date: 2024-09-05 23:45:46.767844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f069cf05997'
down_revision = 'af8e2b81b837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('purchase_link')

    # ### end Alembic commands ###
