"""Add cover_image to Book model

Revision ID: d3e3624614a2
Revises: 39fdbfa96bdf
Create Date: 2024-09-03 14:11:33.555381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e3624614a2'
down_revision = '39fdbfa96bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
